# Generated by Django 4.0.3 on 2022-03-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca',
            name='website',
        ),
        migrations.AddField(
            model_name='ca',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
