# Generated by Django 4.0.3 on 2022-03-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_ca_website_ca_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='address',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
