# Generated by Django 4.0.3 on 2022-03-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_ca_address_alter_contactperson_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
