# Generated by Django 4.0.3 on 2022-03-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_contactperson_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
