# Generated by Django 4.0.3 on 2022-03-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_service_report_delete_report_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('classOneCertificates', models.IntegerField(blank=True, default=0)),
                ('classTwoCertificates', models.IntegerField(blank=True, default=0)),
                ('classThreeCertificates', models.IntegerField(blank=True, default=0)),
                ('eSigns', models.IntegerField(blank=True, default=0)),
                ('lastInternalAuditDate', models.DateField(blank=True, null=True)),
                ('lastExternalAuditDate', models.DateField(blank=True, null=True)),
                ('campaign', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='report.ca')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('organizationName', models.CharField(max_length=100)),
                ('totalDigitalCertificates', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='report.report')),
            ],
        ),
    ]
