# Generated by Django 4.0.3 on 2022-03-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_classonecertificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='classThreeCertificates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='classTwoCertificates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='eSigns',
            field=models.IntegerField(default=0),
        ),
    ]
