# Generated by Django 4.0.3 on 2022-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_report_classthreecertificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='classOneCertificates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='classThreeCertificates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='classTwoCertificates',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='eSigns',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
